# fly.toml app configuration file generated for django-website-patient-glade-7308 on 2025-03-20T09:37:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-website-patient-glade-7308'
primary_region = "ams"
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = false # Disable HTTPS enforcement if you don't have SSL configured
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[health_checks]
  grace_period = "30s"
  interval = "30s"
  timeout = "10s"
  retries = 3
  path = "/health"  # Ensure you have a health endpoint that responds correctly
  port = 8000
